Rdruon/fix block maps
whamcloud/lustrefs-exporter pull request #35
Opened 2023-10-25 15:14 UTC by RDruon

See https://github.com/whamcloud/lustre-collector/pull/70

2023-10-25 15:14 UTC, jgrund commented on src/brw_stats.rs
> +            _ => continue,
Shouldn't we return the new stats?

2023-10-25 15:15 UTC, RDruon commented on src/brw_stats.rs
> +            _ => continue,
We could, any idea what should be the help description?

2023-10-25 15:26 UTC, jgrund commented on src/brw_stats.rs
> +            _ => continue,
Something minimal for now. We can fill in detail later.

2023-10-25 16:50 UTC, jgrund approved these changes

2023-10-25 16:51 UTC, jgrund requested changes
Deb / spec / metadata files also need updating.

2023-10-26 06:57 UTC, RDruon commented
> Deb / spec / metadata files also need updating.

Thanks, updated.

2023-10-26 12:41 UTC, jgrund approved these changes

2023-10-26 12:41 UTC, merged